export interface WorldGarment {
  id: string;
  label: string;
  category: 'women' | 'men' | 'children' | 'modern';
  categoryLabel: string;
  region: string;
  continent?: 'Africa' | 'Asia' | 'Europe' | 'Americas' | 'Contemporary';
  flagEmoji?: string;
  curatorNote?: string;
  culturalHeritage: string;
  description: string;
  silhouetteNotes: string;
  basePriceNaira: number;
  imageUrl: string;
  recommendedFabrics: string[];
  turnaroundDays: number;
}

export type SupportedCurrency = 'NGN' | 'USD' | 'EUR' | 'GBP';

export function formatPrice(naira: number, currency: SupportedCurrency = 'NGN'): string {
  switch (currency) {
    case 'USD':
      return `$${Math.round(naira / 1550).toLocaleString('en-US')}`;
    case 'EUR':
      return `€${Math.round(naira / 1680).toLocaleString('en-US')}`;
    case 'GBP':
      return `£${Math.round(naira / 1960).toLocaleString('en-US')}`;
    case 'NGN':
    default:
      return `₦${naira.toLocaleString('en-NG')}`;
  }
}

export const WORLD_COLLECTION: WorldGarment[] = [
  {
    id: 'women_sari',
    label: 'Indian Silk Sari & Lehenga',
    category: 'women',
    categoryLabel: "Women's Couture",
    region: 'South Asia · India',
    continent: 'Asia',
    flagEmoji: '🇮🇳',
    curatorNote: 'Crimson silk handloom woven with pure metallic zardozi threading and sculptural drape.',
    culturalHeritage: 'Ancient Indian handloom artistry reimagined with structural couture tailoring and pure silk weaves.',
    description: 'Bespoke crimson and gold silk sari lehenga with intricate hand-embroidered zardozi and architectural draping.',
    silhouetteNotes: 'Fitted corset-style choli bodice with sweeping pleated flared lehenga and hand-pleated pallu drape.',
    basePriceNaira: 55000,
    imageUrl: '/atelier/women-sari.jpg',
    recommendedFabrics: ['Silk Satin', 'Velvet', 'Everyday Cotton'],
    turnaroundDays: 8,
  },
  {
    id: 'women_kimono',
    label: 'Tailored Silk Kimono',
    category: 'women',
    categoryLabel: "Women's Couture",
    region: 'East Asia · Japan',
    continent: 'Asia',
    flagEmoji: '🇯🇵',
    curatorNote: 'Kyoto textile precision structured into a minimalist architectural silk silhouette.',
    culturalHeritage: 'Centuries of Kyoto textile discipline sculpted into modern architectural minimalist tailoring.',
    description: 'Contemporary silk kimono in deep indigo and silver weaves with structured obi sash and modern drape.',
    silhouetteNotes: 'Straight-cut T-silhouette with broad kimono sleeves, reinforced tailored collar, and precision wrapped obi sash.',
    basePriceNaira: 48000,
    imageUrl: '/atelier/women-kimono.jpg',
    recommendedFabrics: ['Silk Satin', 'Linen Blend'],
    turnaroundDays: 8,
  },
  {
    id: 'women_boubou',
    label: 'Senegalese Grand Boubou & Aso-Oke Gown',
    category: 'women',
    categoryLabel: "Women's Couture",
    region: 'West Africa · Senegal & Nigeria',
    continent: 'Africa',
    flagEmoji: '🇸🇳',
    curatorNote: 'Royal West African damask with sculpted batwing volume and hand-woven aso-oke finish.',
    culturalHeritage: 'Royal West African ceremonial grandeur combining hand-dyed damask, gold thread embroidery, and Yoruba aso-oke craftsmanship.',
    description: 'Opulent emerald and gold damask grand boubou with sculpted neckline, fluid draping, and hand-woven aso-oke finish.',
    silhouetteNotes: 'Voluminous batwing flowing outer boubou over an engineered tailored inner sheath gown with sculpted keyhole neck.',
    basePriceNaira: 60000,
    imageUrl: '/atelier/women-boubou.jpg',
    recommendedFabrics: ['Everyday Cotton', 'Silk Satin', 'Velvet'],
    turnaroundDays: 9,
  },
  {
    id: 'women_kaftan',
    label: 'Moroccan Royal Kaftan',
    category: 'women',
    categoryLabel: "Women's Couture",
    region: 'North Africa · Morocco',
    continent: 'Africa',
    flagEmoji: '🇲🇦',
    curatorNote: 'Sapphire velvet adorned with authentic Fez sfifa braid and hand-knotted aakad closures.',
    culturalHeritage: 'Fez and Marrakech royal tailoring lineage adorned with handcrafted sfifa braiding and aakad buttons.',
    description: 'Sapphire velvet and champagne silk royal kaftan with authentic sfifa gold thread embroidery and structured belt.',
    silhouetteNotes: 'Floor-length column dress with split front hem, bell cuffs, and cinchable metallic mdamma belt.',
    basePriceNaira: 52000,
    imageUrl: '/atelier/women-kaftan.jpg',
    recommendedFabrics: ['Velvet', 'Silk Satin'],
    turnaroundDays: 8,
  },
  {
    id: 'women_aodai',
    label: 'Vietnamese Ao Dai Ensemble',
    category: 'women',
    categoryLabel: "Women's Couture",
    region: 'Southeast Asia · Vietnam',
    continent: 'Asia',
    flagEmoji: '🇻🇳',
    curatorNote: 'Elongated silk tunic with imperial court neckline floating over wide-leg trousers.',
    culturalHeritage: 'Huế imperial court tailoring refined into an iconic elongated silk silhouette of timeless poise.',
    description: 'Graceful ruby red silk tunic with high collar, hand-stitched floral accents, and tailored flowing trousers.',
    silhouetteNotes: 'Form-hugging silk tunic slit from the natural waist into front and back panels over wide-leg trousers.',
    basePriceNaira: 42000,
    imageUrl: '/atelier/women-aodai.jpg',
    recommendedFabrics: ['Silk Satin', 'Linen Blend'],
    turnaroundDays: 7,
  },
  {
    id: 'women_hanbok',
    label: 'Modern Silk Hanbok',
    category: 'women',
    categoryLabel: "Women's Couture",
    region: 'East Asia · South Korea',
    continent: 'Asia',
    flagEmoji: '🇰🇷',
    curatorNote: 'Blush pink bell chima skirt paired with cropped ivory jeogori and clean goreum ribbons.',
    culturalHeritage: 'Joseon dynasty formal aesthetics reimagined with contemporary haute couture volume and clean lines.',
    description: 'Modern atelier silk hanbok with soft blush chima skirt, ivory jeogori jacket, and minimalist goreum ribbons.',
    silhouetteNotes: 'Cropped curved-hem jeogori bolero jacket over an empire-waist bell chima skirt with generous structural folds.',
    basePriceNaira: 46000,
    imageUrl: '/atelier/women-hanbok.jpg',
    recommendedFabrics: ['Silk Satin', 'Linen Blend'],
    turnaroundDays: 8,
  },
  {
    id: 'women_suit',
    label: 'Bespoke Evening Tuxedo Suit',
    category: 'women',
    categoryLabel: "Women's Couture",
    region: 'Contemporary International',
    continent: 'Contemporary',
    flagEmoji: '🌐',
    curatorNote: 'Obsidian virgin wool power tuxedo with silk satin peak lapels and fluid palazzo trousers.',
    culturalHeritage: "Modern architectural women's tailoring challenging evening wear norms with sharp sartorial authority.",
    description: 'Sculpted obsidian wool tuxedo suit with satin peak lapels and wide-leg pressed trousers for high-profile evening events.',
    silhouetteNotes: 'Single-button suppressed-waist jacket with silk satin lapels paired with high-rise pleated palazzo trousers.',
    basePriceNaira: 58000,
    imageUrl: '/atelier/women-suit.jpg',
    recommendedFabrics: ['Cashmere Blend', 'Everyday Cotton'],
    turnaroundDays: 9,
  },
  {
    id: 'women_huipil',
    label: 'Oaxaca Huipil & Andean Woven Gown',
    category: 'women',
    categoryLabel: "Women's Couture",
    region: 'Latin America · Mexico & Andes',
    continent: 'Americas',
    flagEmoji: '🇲🇽',
    curatorNote: 'Terracotta backstrap-loom weaving integrated into sculpted pencil skirt couture.',
    culturalHeritage: 'Indigenous backstrap-loom weaving from Mesoamerica and the Andes integrated into contemporary bespoke couture.',
    description: 'Tailored couture dress inspired by traditional Oaxaca loom-weaving, terracotta geometric patterns and modern silhouette.',
    silhouetteNotes: 'Geometric square-cut bodice with engineered waist darting and tailored pencil skirt hem with subtle side vent.',
    basePriceNaira: 45000,
    imageUrl: '/atelier/women-huipil.jpg',
    recommendedFabrics: ['Everyday Cotton', 'Linen Blend'],
    turnaroundDays: 8,
  },
  {
    id: 'women_nordic',
    label: 'Nordic Heritage Wool Gown',
    category: 'women',
    categoryLabel: "Women's Couture",
    region: 'Northern Europe · Scandinavia',
    continent: 'Europe',
    flagEmoji: '🇳🇴',
    curatorNote: 'Midnight navy virgin wool with modernist floral crewelwork and pewter filigree clasp.',
    culturalHeritage: 'Scandinavian bunad and folk wool craftsmanship adapted for modern black-tie and winter gala celebrations.',
    description: 'Tailored virgin wool midnight navy evening dress with modernist floral crewelwork and handcrafted silver filigree clasps.',
    silhouetteNotes: 'Fitted corset-inspired bodice with sculpted shoulder straps, pleated heavy wool skirt, and pewter closure hardware.',
    basePriceNaira: 50000,
    imageUrl: '/atelier/women-nordic.jpg',
    recommendedFabrics: ['Cashmere Blend', 'Everyday Cotton'],
    turnaroundDays: 9,
  },
  {
    id: 'men_agbada',
    label: 'Ceremonial Obsidian Agbada',
    category: 'men',
    categoryLabel: "Men's Tailoring",
    region: 'West Africa · Nigeria',
    continent: 'Africa',
    flagEmoji: '🇳🇬',
    curatorNote: 'Regal four-piece agbada crafted from heavy damask with geometric gold chest embroidery.',
    culturalHeritage: 'The pinnacle of West African prestige tailoring, worn by dignitaries and leaders across generations.',
    description: 'Four-piece grand agbada tailored from heavy textured wool and damask with intricate geometric chest embroidery.',
    silhouetteNotes: 'Voluminous cape-like winged robe resting on broad shoulders over a fitted buba tunic and tapered sokoto trousers.',
    basePriceNaira: 65000,
    imageUrl: '/atelier/men-agbada.jpg',
    recommendedFabrics: ['Everyday Cotton', 'Cashmere Blend'],
    turnaroundDays: 10,
  },
  {
    id: 'men_sherwani',
    label: 'Brocade Royal Sherwani',
    category: 'men',
    categoryLabel: "Men's Tailoring",
    region: 'South Asia · India & Pakistan',
    continent: 'Asia',
    flagEmoji: '🇵🇰',
    curatorNote: 'Ivory and muted gold brocade with high mandarin collar, jeweled buttons and churidar.',
    culturalHeritage: 'Mughal and princely heritage tailoring balancing formal military structure with opulent brocade silk.',
    description: 'Ivory and muted gold brocade sherwani jacket with mandarin collar, jeweled buttons, and fitted churidar trousers.',
    silhouetteNotes: 'Knee-length structured frock coat with high mandarin collar, sharp shoulder canvassing, and flared skirt vents.',
    basePriceNaira: 58000,
    imageUrl: '/atelier/men-sherwani.jpg',
    recommendedFabrics: ['Silk Satin', 'Cashmere Blend'],
    turnaroundDays: 9,
  },
  {
    id: 'men_suit',
    label: 'Savile Row Double-Breasted Suit',
    category: 'men',
    categoryLabel: "Men's Tailoring",
    region: 'European Contemporary',
    continent: 'Europe',
    flagEmoji: '🇬🇧',
    curatorNote: 'Canvassed charcoal chalk stripe wool with roped sleeveheads and double-pleat trousers.',
    culturalHeritage: "The global benchmark of gentleman's sartorial precision, hand-canvassed for a lifetime of wear.",
    description: 'Impeccably structured double-breasted charcoal wool suit with fine chalk stripe and precision hand-canvassed chest.',
    silhouetteNotes: 'Six-on-two double-breasted button configuration, roped sleeveheads, and double-pleated trousers with side adjusters.',
    basePriceNaira: 62000,
    imageUrl: '/atelier/men-suit.jpg',
    recommendedFabrics: ['Cashmere Blend', 'Everyday Cotton'],
    turnaroundDays: 9,
  },
  {
    id: 'men_haori',
    label: 'Modern Haori & Pleated Hakama',
    category: 'men',
    categoryLabel: "Men's Tailoring",
    region: 'East Asia · Japan',
    continent: 'Asia',
    flagEmoji: '🇯🇵',
    curatorNote: 'Matte black structured haori overcoat with silk tie cord over pleated hakama culottes.',
    culturalHeritage: 'Traditional samurai formal attire translated into contemporary minimalist urban tailoring.',
    description: 'Architectural structured matte black haori overcoat paired with deep slate tailored hakama trousers and inner tunic.',
    silhouetteNotes: 'Open-front relaxed overjacket with haori-himo tie cord worn over deep pleated wide-leg hakama culottes.',
    basePriceNaira: 48000,
    imageUrl: '/atelier/men-haori.jpg',
    recommendedFabrics: ['Everyday Cotton', 'Linen Blend'],
    turnaroundDays: 8,
  },
  {
    id: 'men_thobe',
    label: 'Crisp Thobe with Royal Bisht Cloak',
    category: 'men',
    categoryLabel: "Men's Tailoring",
    region: 'Middle East · Gulf & Levant',
    continent: 'Africa',
    flagEmoji: '🇸🇦',
    curatorNote: 'Pristine white cotton thobe with sheer black bisht cape and hand-stitched zari gold trim.',
    culturalHeritage: 'The ceremonial attire of royalty and nobility across the Arabian Peninsula, worn at weddings and national ceremonies.',
    description: 'Crisp tailored white cotton thobe paired with a sheer black and gold-embossed ceremonial bisht cape.',
    silhouetteNotes: 'Clean ankle-length tunic with stiff banded collar paired with an oversized sheer bisht cloak with hand-stitched zari gold trim.',
    basePriceNaira: 54000,
    imageUrl: '/atelier/men-thobe.jpg',
    recommendedFabrics: ['Everyday Cotton', 'Linen Blend'],
    turnaroundDays: 7,
  },
  {
    id: 'children_formal',
    label: 'Petite Ceremonial Kaftan & Formal Suit',
    category: 'children',
    categoryLabel: "Children's Wear Accent",
    region: 'Global Heritage',
    continent: 'Contemporary',
    flagEmoji: '✨',
    curatorNote: 'Miniature bespoke formal attire tailored in breathable cream linen with gold accents.',
    culturalHeritage: 'Handcrafted miniature couture designed for generational celebrations, family weddings, and milestone occasions.',
    description: 'Comfortable breathable cream linen ceremonial kaftan and slim trousers with subtle gold stitch accents for family occasions.',
    silhouetteNotes: 'Relaxed tunic with room for easy movement, soft elasticated comfort waistband trousers, and hypoallergenic stitching.',
    basePriceNaira: 28000,
    imageUrl: '/atelier/children-formal.jpg',
    recommendedFabrics: ['Linen Blend', 'Everyday Cotton'],
    turnaroundDays: 6,
  },
  {
    id: 'modern_coat',
    label: 'Minimalist Cashmere Wrap Coat',
    category: 'modern',
    categoryLabel: 'Modern Fusion',
    region: 'Global Contemporary',
    continent: 'Contemporary',
    flagEmoji: '🧥',
    curatorNote: 'Unisex camel cashmere wrap coat merging kimono wrapping with Nordic minimalism.',
    culturalHeritage: 'Cross-cultural fusion bridging Japanese kimono wrapping with Scandinavian minimalism and high-end street tailoring.',
    description: 'Contemporary unisex camel cashmere wrap coat with sculpted storm flap and wide-leg pressed trousers.',
    silhouetteNotes: 'Relaxed dropped-shoulder trench silhouette with unstructured shawl collar, deep pockets, and self-tie cashmere belt.',
    basePriceNaira: 64000,
    imageUrl: '/atelier/modern-coat.jpg',
    recommendedFabrics: ['Cashmere Blend', 'Velvet'],
    turnaroundDays: 9,
  },
];
